// RobotBuilder Version: 1.5

package org.usfirst.frc2337.RobotProject;

import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;



import org.usfirst.frc2337.RobotProject.commands.*;
import org.usfirst.frc2337.RobotProject.subsystems.*;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot {

	Command autonCommand;
    SendableChooser autonChooser;

    public static OI oi;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static ChassisPID chassis;
    public static Lift lift;
    public static Intake intake;
    public static Pneumatics pneumatics;
    public static IntakePneumatics intakePneumatics;
    public static Kicker kicker;
    public static ContainerArmLift containerArmLift;
    public static ContainerArmExtension conExtension;
    public static LED led;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    public void robotInit() {
    RobotMap.init();
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        chassis = new ChassisPID();
        lift = new Lift();
        intake = new Intake();
        pneumatics = new Pneumatics();
        intakePneumatics = new IntakePneumatics();
        kicker = new Kicker();
        containerArmLift = new ContainerArmLift();
        conExtension = new ContainerArmExtension();
        led = new LED();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // OI must be constructed after subsystems. If the OI creates Commands 
        //(which it very likely will), subsystems are not guaranteed to be 
        // constructed yet. Thus, their requires() statements may grab null 
        // pointers. Bad news. Don't move it.
        oi = new OI();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        
      //AUTON CHOOSER
        //Instantiate the command used for the autonomous period
        
        //SmartDashboard Auton Selector
        autonChooser = new SendableChooser();
        autonChooser.addObject("Move Straight to Auton Zone", new AutonDriveAtSpeedForTime(0.5,0.5)); //speed, time
        autonChooser.addObject("Move 1 Tote to Auton Zone", new Auton_1Tote());
        autonChooser.addObject("Kettering Comp Move 3F -COMP Gyro Tote- 3 Totes", new Auton_3ToteF_AfterKetteringWithTote());
        autonChooser.addDefault("Move 3 Totes J - added velocity ramp up & isFinished timer", new Auton_3ToteJ());
        autonChooser.addObject("Move 3 Totes K - added strafe encoder on end", new Auton_3ToteK());
        autonChooser.addObject("Move 3 Totes K_Wrapper - alternate timer by nesting commands", new Auton_3ToteK_Wrapper());
        autonChooser.addObject("Do Nothing", new DoNothing());
        SmartDashboard.putData("Auton Chooser", autonChooser);
    }
    
    /**
     * This function is called periodically while the robot is on, regardless of current mode.
     * The most obvious use for this is continuously updating SmartDashboard outputs.
     */
    public void robotPeriodic() {
    	LiveWindow.run();
    	
    	
    	
    	SmartDashboard.putData		("Scheduled Commands", 			Scheduler.getInstance());
    	
    	//Chassis
        SmartDashboard.putNumber	("Chassis PID Setpoint", 			Robot.chassis.getSetpoint());
    	SmartDashboard.putNumber	("Chassis PID Position", 			Robot.chassis.getPosition());
    	SmartDashboard.putNumber	("Chassis Auton Encoder Position",	Robot.chassis.readAutonEncoder());
    	SmartDashboard.putNumber	("Chassis Strafe Encoder Position",	Robot.chassis.readStrafeEncoder());
    	SmartDashboard.putBoolean	("Chassis Tote Sensor", 			Robot.chassis.isToteSensor());
    	
    	//Intake
    	SmartDashboard.putBoolean	("Intake Extended", 			Robot.intakePneumatics.getArmPosition());
    	
    	//Lift
    	SmartDashboard.putBoolean	("Practice Bot Positions",		Robot.lift.isCompetitionBot());
    	SmartDashboard.putNumber	("Lift Variable: Base", 		Robot.lift.base);
    	SmartDashboard.putNumber	("Lift Variable: Tote", 		Robot.lift.tote);
    	SmartDashboard.putNumber	("Lift Variable: Type", 		Robot.lift.type);
    	SmartDashboard.putNumber	("Lift Variable: Array", 		Robot.lift.setarray[Robot.lift.base][Robot.lift.tote]);
        SmartDashboard.putNumber	("Lift Current Position",		Robot.lift.getSetpoint());
        SmartDashboard.putNumber	("Lift New Position",			Robot.lift.getPosition());
        
        //Kicker
        SmartDashboard.putBoolean	("Kicker Position", 			Robot.kicker.getPosition());
        SmartDashboard.putBoolean	("Kicker AutoKick",				Robot.kicker.isAutoKick());
        
        //Container Arm
        SmartDashboard.putBoolean	("Container Arm Extended", 		Robot.conExtension.getSolenoidPosition());

        //GYRO - IMU
        SmartDashboard.putBoolean(  "IMU_Connected",        RobotMap.imu.isConnected());
        SmartDashboard.putBoolean(  "IMU_IsCalibrating",    RobotMap.imu.isCalibrating());
        SmartDashboard.putNumber(   "IMU_Yaw",              RobotMap.imu.getYaw());
        
    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    public void disabledInit(){

    }

    public void disabledPeriodic() {
        Scheduler.getInstance().run();
        robotPeriodic();
    }

    public void autonomousInit() {
        // schedule the autonomous command (example)
    	RobotMap.imu.zeroYaw();
    	Robot.chassis.initEncoder();
    	autonCommand = (Command) autonChooser.getSelected();
        if (autonCommand != null) autonCommand.start();
    }

    /**
     * This function is called periodically during autonomous
     */
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
        robotPeriodic();
    }

    public void teleopInit() {
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to 
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonCommand != null) autonCommand.cancel();
        
    	RobotMap.imu.zeroYaw();
    	Robot.chassis.disable();
    	Robot.lift.setTeleopLiftSpeed();

    }

    /**
     * This function is called periodically during operator control
     */
    public void teleopPeriodic() {
        Scheduler.getInstance().run();
        robotPeriodic();
    }

    /**
     * This function is called periodically during test mode
     */
    public void testPeriodic() {
        LiveWindow.run();
        robotPeriodic();
    }
}
