// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject;

import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc2337.RobotProject.commands.*;
import org.usfirst.frc2337.RobotProject.subsystems.*;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot {

	Command autonCommand;
    SendableChooser autonChooser;

    public static OI oi;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static ChassisPID chassis;
    public static Lift lift;
    public static Intake intake;
    public static Pneumatics pneumatics;
    public static IntakePneumatics intakePneumatics;
    public static Kicker kicker;
    public static ContainerArmMotor conArm;
    public static ContainerArmExtension conExtension;
    public static LED led;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    public void robotInit() {
    RobotMap.init();
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        chassis = new ChassisPID();
        lift = new Lift();
        intake = new Intake();
        pneumatics = new Pneumatics();
        intakePneumatics = new IntakePneumatics();
        kicker = new Kicker();
        conArm = new ContainerArmMotor();
        conExtension = new ContainerArmExtension();
        led = new LED();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // OI must be constructed after subsystems. If the OI creates Commands 
        //(which it very likely will), subsystems are not guaranteed to be 
        // constructed yet. Thus, their requires() statements may grab null 
        // pointers. Bad news. Don't move it.
        oi = new OI();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        
      //AUTON CHOOSER
        //Instantiate the command used for the autonomous period
        
        //SmartDashboard Auton Selector
        autonChooser = new SendableChooser();
        autonChooser.addObject("Move Straight to Auton Zone", new AutonDriveAtSpeedForTime(0.5,3.0)); //speed, time
        autonChooser.addObject("Move 1 Tote to Auton Zone", new Auton_1Tote());
        //autonChooser.addObject("Move 2 Totes to Auton Zone", new Auton2Tote());
        autonChooser.addDefault("Move 3 Totes to Auton Zone", new Auton_3Tote());
        autonChooser.addObject("Move 3B Totes to Auton Zone", new Auton_3ToteB());
        //autonChooser.addObject("Move 1 Container to Auton Zone", new Auton1Container());
        //autonChooser.addObject("Move 2 Containers to Auton Zone", new Auton2Container());
        //autonChooser.addObject("Move 3 Containers to Auton Zone", new Auton3Container());
        autonChooser.addObject("Do Nothing", new DoNothing());
        SmartDashboard.putData("Auton Chooser", autonChooser);
        
    }
    
    /**
     * This function is called periodically while the robot is on, regardless of current mode.
     * The most obvious use for this is continuously updating SmartDashboard outputs.
     */
    public void robotPeriodic() {
    	SmartDashboard.putData		("Scheduled Commands", 			Scheduler.getInstance());
    	
    	//Chassis
        SmartDashboard.putNumber	("Chassis PID Setpoint", 		Robot.chassis.getSetpoint());
    	SmartDashboard.putNumber	("Chassis PID Position", 		Robot.chassis.getPosition());
    	SmartDashboard.putNumber	("Chassis Encoder Position",	Robot.chassis.readEncoderDistance());
    	SmartDashboard.putBoolean	("Chassis Tote Sensor", 		Robot.chassis.isToteSensor());
    	
    	//Intake
    	SmartDashboard.putBoolean	("Intake Extended", 			Robot.intakePneumatics.getArmPosition());
    	
    	//Lift
    	SmartDashboard.putBoolean	("Practice Bot Positions",		Robot.lift.isPracticeBot());
    	SmartDashboard.putNumber	("Lift Variable: Base", 		Robot.lift.base);
    	SmartDashboard.putNumber	("Lift Variable: Tote", 		Robot.lift.tote);
    	SmartDashboard.putNumber	("Lift Variable: Type", 		Robot.lift.type);
    	SmartDashboard.putNumber	("Lift Variable: Array", 		Robot.lift.setarray[Robot.lift.base][Robot.lift.tote]);
        SmartDashboard.getBoolean	("Lift Tote Switch", 			Robot.lift.LiftAutoTote());
        
        //Kicker
        SmartDashboard.putBoolean	("Kicker Position", 			Robot.kicker.getPosition());
        SmartDashboard.putBoolean	("Kicker Tote Sensor", 			Robot.kicker.isFingerSensor());
        SmartDashboard.putBoolean	("Kicker AutoKick",				Robot.kicker.isAutoKick());
        
        //Container Arm
        SmartDashboard.putBoolean	("Container Arm Extended", 		Robot.conExtension.getSolenoidPosition());
    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    public void disabledInit(){

    }

    public void disabledPeriodic() {
        Scheduler.getInstance().run();
        robotPeriodic();
    }

    public void autonomousInit() {
        // schedule the autonomous command (example)
    	autonCommand = (Command) autonChooser.getSelected();
        if (autonCommand != null) autonCommand.start();
    }

    /**
     * This function is called periodically during autonomous
     */
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
        robotPeriodic();
    }

    public void teleopInit() {
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to 
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonCommand != null) autonCommand.cancel();
    }

    /**
     * This function is called periodically during operator control
     */
    public void teleopPeriodic() {
        Scheduler.getInstance().run();
        robotPeriodic();
    }

    /**
     * This function is called periodically during test mode
     */
    public void testPeriodic() {
        LiveWindow.run();
        robotPeriodic();
    }
}
