package org.usfirst.frc2337.RobotProject.commands;
// RobotBuilder Version: 1.5


import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc2337.RobotProject.Robot;
import org.usfirst.frc2337.RobotProject.RobotMap;

/**
 *
 */
public class  Auton_ActivateMotors extends Command {
	double left; //Left Motor
	double right; //Right Motor
	
    public Auton_ActivateMotors(double left, double right) {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.intake);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        
        this.left = left; //Make Variables usable in this comand
        this.right = right;
    }
    
    

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.intake.setLeftArmSpeed(left);
    	Robot.intake.setRightArmSpeed(right);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	//Set the Speed of the arms
 //   	Robot.intake.setLeftArmSpeed(left);
 //   	Robot.intake.setRightArmSpeed(right);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return true;
    }

    // Called once after isFinished returns true
    protected void end() {
    //	RobotMap.intakeLeftArmMotor.set(0);
 //   	RobotMap.intakeRightArmMotor.set(0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	this.end();
    	
    }
}
