// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Auton_1Tote extends CommandGroup {
    
    public  Auton_1Tote() {
        // Add Commands here:
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());

    	
    	addSequential(new LIFT_PidSet(2,1)); 						//lift tote to position 2 (also to simulate end of 3-tote auton)
    												// kick out pancake cylinder in preperation to push tote(s)
    	addParallel(new LIFT_PidSet(0,1));							//drop tote to floor
    	addSequential(new AutonStrafeAtSpeedForTime(1.0,1.9));		//strafe out to auton zone...  Need to check distance
    	addSequential(new AutonStrafeAtSpeedForTime(-1.0,0.5));		//strafe back away from tote(s)
	
    }
}
