// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject.commands;
import org.usfirst.frc2337.RobotProject.Robot;
import org.usfirst.frc2337.RobotProject.RobotMap;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *  With Strafe Encoder, Acceleration Profile, Tuned PID on drive encoder, and Gyro(IMU).
 */
public class Auton_3ToteK_Wrapper extends CommandGroup {
	
    public  Auton_3ToteK_Wrapper() {
        // Add Commands here:
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
    	
    	addSequential(new Auton_3ToteK_sub(),14);
    	
    	
    	addSequential(new Auton_LIFT_PidSet(Robot.lift.autonPos1));		//lower lift to release totes
    	addSequential(new KICKER_KickIn());							//bring kicker in
    	addSequential(new AutonStrafeAtSpeedForTime(1.0,0.1));			//move way from stacked totes to get auton score
    	addSequential(new Auton_LIFT_PidSet(Robot.lift.autonPos12));	//lower lift to floor to get ready for teleop
    	
    }
 
}
