// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2337.RobotProject.Robot;

	/**
	 * Strafe using Encoder. 
	 * Parameters are distance(ticks) and speed.
	 * Needs Negative speed - towards lift.  Approx 86 ticks per foot.
	 */
	public class  AutonEncoderStrafeIn extends Command {
		
		double speed;    	//negative is towards totes/auton zone
		int distance;		//Auton zone is approx 975 ticks
		
	    public AutonEncoderStrafeIn(double speed, int distance) {
	    	this.distance = distance;
	    	this.speed = speed;
	        // Use requires() here to declare subsystem dependencies
	        // eg. requires(chassis);

	        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	        requires(Robot.chassis);

	    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	    }

	    // Called just before this Command runs the first time
	    protected void initialize() {
	    	//Robot.chassis.resetStrafeEncoder();    			 //using seperate command to do this
	    }

	    // Called repeatedly when this Command is scheduled to run
	    protected void execute() {
	    	Robot.chassis.driveMecanum(0, speed, 0);
	    }

	    // Make this return true when this Command no longer needs to run execute()
	    protected boolean isFinished() {
	        return ((Robot.chassis.readStrafeEncoder() > distance) || isTimedOut());
	    }

	    // Called once after isFinished returns true
	    protected void end() {
	    	Robot.chassis.driveMecanum(0, 1, 0);
	    	Robot.chassis.stopMotors();
	    }
	    
	    // Called when another command which requires one or more of the same
	    // subsystems is scheduled to run
	    protected void interrupted() {
	    	end();
	    }
	}