// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Auton_StepContainer extends CommandGroup {
    
    public  Auton_StepContainer() {
        // Add Commands here:


       	addParallel(new Auton_ChassisPidSet(10)); 	
    	addSequential(new MultiPurposeGrabber_Open()); 						//lift tote to position 2 (also to simulate end of 3-tote auton)
    	addSequential(new Auton_ChassisPidSet(-300));

	
    }
}
