// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject.commands;
import org.usfirst.frc2337.RobotProject.Robot;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Auton_OneContainer extends CommandGroup {
    
    public  Auton_OneContainer() {
    	addSequential(new GyroReset());
    	addSequential(new ResetEncoder());
    	addSequential(new ResetStrafeEncoder());
    	
    	//addSequential(new LIFT_PidSetBlueButton());
    	addSequential(new Auton_LIFT_PidSet(Robot.lift.autonPos13));
    	addSequential(new KICKER_KickOut());
    	addSequential(new AutonWait(1));
    	
    	addSequential(new Auton_ChassisPidSet(800));
    	//addSequential(new AutonTurnDegreesCwPos(90));
    	//addSequential(new AutonEncoderStrafeOut(0.5, 5));
	
    }
}
