// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject.commands;
import org.usfirst.frc2337.RobotProject.Robot;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutonRandomTest extends CommandGroup {
	
    public  AutonRandomTest() {
        // Add Commands here:
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
    	addSequential(new ResetEncoder());
    	addSequential(new GyroReset());

    	addSequential(new Auton_ChassisPidSetWithToteSensor(450));
    	//addSequential(new Auton_ChassisPidSetAfterToteSensor(158));					//drive to 2nd tote // from 510 at kettering  //527 at Kettering
    }
}
