// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject.commands;
import org.usfirst.frc2337.RobotProject.Robot;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Auton_Summary_Initial_Block2_No_Can extends CommandGroup {
    
    public  Auton_Summary_Initial_Block2_No_Can() {
     	addParallel(new KICKER_KickOut());
    	addSequential(new Auton_LIFT_PidSet(Robot.lift.autonPos1));   	//lift tote to position 1
    	addSequential(new AutonDriveAtSpeedForTimeGyro(-0.3, 0.2));		//drive back to clear can lid when lifting
    	addSequential(new Auton_LIFT_PidSet(Robot.lift.autonPos5));   	//lift tote to position 1
    	//addParallel(new Auton_LIFT_PidSet(Robot.lift.autonPos2));		//lift tote to position to clear can
    	addSequential(new AutonEncoderStrafeOut(1, 10));				// changed at kettering for container arm  0.5


    	//DRIVE TO TOTE 2   	
    	//addSequential(new AutonDriveForEncoderGyroIterative(290));			//ramp speed up and drive past container
    	addSequential(new AutonDriveForTimeGyroIterative(.85));			//ramp speed up and drive past container

    	addSequential(new Auton_ChassisPidSetWithToteSensor(600));		//drive to 2nd tote, reset setpoint when sensor sees tote
    	//addSequential(new AutonWait(1));
    	addSequential(new Auton_LIFT_PidSet(Robot.lift.autonPos2));		//lower tote to pos 2 in parallel while driving to next tote

    	//    addSequential(new Auton_ChassisPidSetFinishFirst());  /// testing........................................
	
    }
}
