// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject.commands;
import org.usfirst.frc2337.RobotProject.Robot;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Auton_1Tote extends CommandGroup {
    
    public  Auton_1Tote() {
        // Add Commands here:
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());

    	addSequential(new ChassisDisable());
    	addSequential(new Auton_LIFT_PidSet(Robot.lift.autonPos1));   	//Lift tote to position 1
    	addParallel(new KICKER_KickOut());
    	addSequential(new AutonEncoderStrafeIn(1, -650));
    	addSequential(new Auton_LIFT_PidSet(Robot.lift.autonPos12));
    	addSequential(new MetaTrolleyBrake_On());
     	addSequential(new KICKER_KickIn());	
	
    }
}
