// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject.commands;
import org.usfirst.frc2337.RobotProject.Robot;
import org.usfirst.frc2337.RobotProject.RobotMap;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *  With Strafe Encoder, Acceleration Profile, Tuned PID on drive encoder, and Gyro(IMU).
 */
public class Auton_Nested_A_WithContainer extends CommandGroup {
	
    public  Auton_Nested_A_WithContainer() {

    	//setTimeout(14.5);											// set Auton timer here
    	setTimeout(14.6);											// set Auton timer here
    	
    	addSequential(new ResetGyro());
    	addSequential(new ResetEncoder());
    	addSequential(new ResetStrafeEncoder());
    	
    	addSequential(new Auton_Summary_GrabContainer());
    	addSequential(new Auton_Summary_Initial_Block2());
    	addSequential(new Auton_Summary_GrabTote2());
    	addSequential(new Auton_Summary_MoveToTote3AndPush());
    	addSequential(new Auton_Summary_TheBigFinish());
    	
    	
    	
    }
    
	protected boolean isFinished() {
		return (isTimedOut() || (RobotMap.imu.getPitch() > 10));
	}
	
	protected void end() {
		//Timer.delay(.1);
		//Robot.lift.setSetpoint(1.8);				//trying to back away from stacked totes to score auton points
		//Robot.kicker.kickIn();
		Robot.intakeExtendArms.armsIn();
		
		/*
		if (RobotMap.imu.getPitch() > 10) {
			Robot.lift.setSetpoint(Robot.lift.getPosition() + .8);
		}
		*/
		
		if (RobotMap.imu.getPitch() > 10) {
			Robot.lift.setSetpoint(Robot.lift.getPosition() + .8);
		}else {
			Robot.lift.setSetpoint(Robot.lift.getPosition() - .1);			
		}
		
		
		for (int i = 0; i < 15; i++) {
			RobotMap.chassisbackLeft.set(0.5);
			RobotMap.chassisbackRight.set(0.5);
			RobotMap.chassisfrontLeft.set(-0.5);
			RobotMap.chassisfrontRight.set(-0.5);
			Timer.delay(.02);
		}
		Robot.intakeOpenArms.openArmsIn();
		Robot.intakeMotors.setIntakeMotorsStop();
	}    
 
}
