package org.usfirst.frc2337.RobotProject.commands;
// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc2337.RobotProject.Robot;

/**
 *
 */
public class  Auton_ChassisPidSet extends Command {

   boolean leave = false;
   double pidset;
    
    public Auton_ChassisPidSet(double pidset) {
    	this.pidset = pidset;
    	
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
    	//requires(Robot.chassis);
    	requires(Robot.chassis);

 
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    		Robot.chassis.enable();
    		Robot.chassis.setSetpoint(pidset);
    		//SmartDashboard.putBoolean("init?", true);
    	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	double pidget = Robot.chassis.getPosition();
    	SmartDashboard.putNumber("pidget", pidget);
    	
    	/*
    	if (pidget > 100) {
    		
    		leave = true;
    	}
    	*/
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	 return Robot.chassis.onTarget();
    }

    // Called once after isFinished returns true
    protected void end() {
    	SmartDashboard.putBoolean("finished?", true);
       //	Robot.chassis.stopMotors();
    	Robot.chassis.disable();
 
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	this.end();
    }
}
