// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class BUTTON_KickIn_LiftDown extends CommandGroup {
    
    public  BUTTON_KickIn_LiftDown() {
        // Add Commands here:
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());


    	addSequential(new KICKER_KickIn());	
    	addSequential(new AutonWait(.15));
    	//addSequential(new LIFT_PidSet(0,1));
    	addSequential(new LIFT_PidSetWithSpeed(0,1, 0.8,-0.9));
   //	addSequential(new LED_TurnOn());

	
    }
    
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }
}
