// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject.commands;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc2337.RobotProject.Robot;

/**
 * Drive with a tank-style drive. The left stick, up and down,
 * is used for the left motors and the right stick, up and down,
 * is used for the right motors.
 */
public class  DriveWithJoystickTank extends Command {

	private Joystick joystickDriver = Robot.oi.joystickDriver;
	private double threshold = 0.1;
	
    public DriveWithJoystickTank() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.chassis);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	double leftValue = joystickDriver.getRawAxis(1);
    	double rightValue = joystickDriver.getRawAxis(5);
    	
    	//Set the values to 0 if the input is below threshold
    	if (Math.abs(leftValue) < threshold) {
    		leftValue = 0;
    	}
    	if (Math.abs(rightValue) < threshold) {
    		rightValue = 0;
    	}
    	
    	// square the inputs (while preserving the sign) to increase fine control while permitting full power
    	if (leftValue >= 0.0) {
            leftValue = (leftValue * leftValue);
        } else {
            leftValue = -(leftValue * leftValue);
        }
        if (rightValue >= 0.0) {
            rightValue = (rightValue * rightValue);
        } else {
            rightValue = -(rightValue * rightValue);
        }
        
        Robot.chassis.driveTank(leftValue, rightValue);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.chassis.stopMotors();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	Robot.chassis.stopMotors();
    }
}
