// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class LIFT_PidSetWhiteButton extends CommandGroup {
    
    public  LIFT_PidSetWhiteButton() {
        // Add Commands here:
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());


    	addSequential(new KICKER_KickIn());					
    	addSequential(new LIFT_PidSet(0,1));

	
    }
}
