// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject.commands;
import org.usfirst.frc2337.RobotProject.Robot;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class LIFT_PidSet1stBlackButton extends CommandGroup {
    
    public  LIFT_PidSet1stBlackButton() {
        // Add Commands here:
        // e.g. addParallel(new Command1());[]\
    	
        //      addSequential(new Command2());
    	

    	if (Robot.lift.getPosition() < 3) {
    	addSequential(new LIFT_PidSetWithSpeed(1,1,.5,-.7)); 					//lift tote to position 2 (also to simulate end of 3-tote auton)
    												// kick out pancake cylinder in preperation to push tote(s)
    	addSequential(new KICKER_KickOut());							//drop tote to floor
    	addSequential(new AutonWait(.15));
    	addSequential(new LIFT_PidSetWithSpeed(2,1,.7,-.7)); 
    	}

	
    }
}
