// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc2337.RobotProject.Robot;
import org.usfirst.frc2337.RobotProject.RobotMap;

/**
 *
 */
public class  LIFT_PidSetMinusRelative extends Command {
	
	public double setpoint;
	
	/**
	 * Resets the Lift setpoint to a relative value from the current set point. 
	 * @param setpoint double value of the relative PID position. Positive or negative.
	 */

    public LIFT_PidSetMinusRelative(double setpoint) {
    	requires(Robot.lift);
    	this.setpoint = setpoint;
    }

    // Called just before this Command runs the first time
    protected void initialize() { 
    	if (Robot.lift.getPosition() > 2.19) {
    	Robot.lift.getPIDController().setInputRange(2.19, Robot.lift.liftTopLimit);
    	}
    	Robot.lift.setSetpointRelative(setpoint);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }
    

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	 return (Robot.lift.onTarget());
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.lift.getPIDController().setInputRange( Robot.lift.liftBottomLimit, Robot.lift.liftTopLimit);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	this.end();
    }
}
