// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.RobotProject.commands;
import org.usfirst.frc2337.RobotProject.Robot;
import org.usfirst.frc2337.RobotProject.RobotMap;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class ScoreButton extends CommandGroup {
    
    public  ScoreButton() {
    	requires(Robot.metaTrolleyBrake);
    	requires(Robot.metaTrolleyGrabber);
    	requires(Robot.intakeExtendArms);
    	requires(Robot.intakeOpenArms);
    	
    	
   addParallel(new INTAKE_ExtendArms_ArmsIn());
   //addParallel(new MetaTrolleyGrabber_Open());	
  // addParallel(new MetaTrolleyBrake_On());	
   //addParallel(new INTAKE_OpenArms_ArmsIn());   

	
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return true;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
